[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py tests/**/*.py
addopts = -ra -q -p celery.contrib.pytest
testpaths = app
pythonpath = app
markers =
    e2e: tests bout-en-bout via navigateur (Playwright)
    slow: tests lents
filterwarnings =
    ignore::DeprecationWarning
    ignore::RuntimeWarning
