# Generated by Django 5.0.6 on 2025-08-15 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code action"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Basse"),
                            ("MED", "Moyenne"),
                            ("HIGH", "Haute"),
                            ("CRIT", "Critique"),
                        ],
                        default="MED",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A_FAIRE", "À faire"),
                            ("EN_COURS", "En cours"),
                            ("EN_TRAITEMENT", "En traitement"),
                            ("CLOTUREE", "Clôturée"),
                            ("ARCHIVEE", "Archivée"),
                        ],
                        default="A_FAIRE",
                        max_length=20,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Échéance"),
                ),
                (
                    "done_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date réalisation"
                    ),
                ),
                (
                    "efficacy_note",
                    models.TextField(blank=True, verbose_name="Évaluation efficacité"),
                ),
                (
                    "j_delta",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Jours de delta"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_liees",
                        to="paa.action",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsables",
                    models.ManyToManyField(
                        blank=True,
                        related_name="actions_responsables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom du plan")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code plan"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("EXCEL", "Excel Externe"),
                            ("INTERNE", "Mode Interne"),
                        ],
                        default="EXCEL",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans_possedes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="paa.action"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="paa.plan"
                    ),
                ),
            ],
            options={
                "unique_together": {("action", "plan")},
            },
        ),
    ]
