# Generated by Django 5.0.6 on 2025-08-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "sheet_name",
                    models.CharField(default="plan d’action", max_length=100),
                ),
                ("header_row", models.PositiveIntegerField(default=11)),
                ("mapping", models.JSONField(default=dict)),
                ("allow_user_creation", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SyncReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="paa.plan"
                    ),
                ),
            ],
        ),
    ]
