# Generated by Django 5.0.6 on 2025-08-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0002_importprofile_syncreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branding", models.JSONField(default=dict)),
                ("colors", models.JSONField(default=dict)),
                ("feature_flags", models.JSONField(default=dict)),
                ("smtp_tested", models.BooleanField(default=False)),
                ("admin_ip_allowlist", models.JSONField(default=list)),
            ],
        ),
    ]
