# Generated by Django 5.0.6 on 2025-08-15 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0003_systemsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="paa.plan"
                    ),
                ),
            ],
        ),
    ]
