# Generated by Django 5.0.6 on 2025-08-15 16:20

import django.contrib.postgres.indexes
import django.db.models.deletion
import paa.models_attachments
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0004_syncschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=paa.models_attachments.attachment_upload_to
                    ),
                ),
                ("mime", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                ("ocr_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="paa.action",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["ocr_text"],
                        name="idx_attachment_ocr_gin",
                        opclasses=["gin_trgm_ops"],
                    )
                ],
            },
        ),
    ]
