# Generated by Django 5.0.6 on 2025-08-15 16:32

import paa.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0006_fulltext_search"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("actor", models.CharField(blank=True, max_length=150)),
                ("verb", models.CharField(max_length=50)),
                ("obj_type", models.CharField(max_length=100)),
                ("obj_id", models.CharField(max_length=64)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("ip", models.CharField(blank=True, max_length=45)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-ts"],
            },
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_password",
            field=paa.crypto.EncryptedTextField(blank=True),
        ),
    ]
