# Generated by Django 5.0.6 on 2025-08-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0009_materialized_view_consolidated"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=64)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
